### ISSUE TITLE
Populating a nested association

### ISSUE THREAD

**Issue by dottodot** [oscarhaggerty/Backbone.Sails#7]
I have the following Comment model with a user association, but is it possible to populate the user on the child collection or would it require modifying the blueprint to achieve this?

````
module.exports = {
  attributes: {
    comment: 'string',
    parent: {
        model: 'Comment'
    },
    children: {
        collection: 'Comment',
        via: 'parent'
    },
    user: {
        model: 'User'
    }
  }
};
```

**Comment by oscarhaggerty** [comment]
Sails doesn't support 'nested' populations. It wouldn't be too difficult to code on the server side, but the security considerations are endless. It would take two round-trips to the database in any case (through waterline).

Your better off just getting the model & populating:

```
coll.get("children", true).findWhere({ name: "Haggerty" }).populate(true).fetch();
```
